version: 2.1

orbs:
  node: circleci/node@5.0.3

jobs:
  publish:
    executor: node/default
    # docker:
    #   -  image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: publish to npm
          command: |
            npm install
            npm run build
            npm set //registery.npmjs.org/:_authToken=$NPM_TOKEN
            npm publish
workflows:
  tagged-build:
    jobs:
      - publish:
          filters:
            branches:
              only:
                - main
                - master
